apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysvc1
  name: mysvc1
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: nginx
  type: ClusterIP
status:
  loadBalancer: {}
