apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      nodePort: 30087
      port: 80
      targetPort: 80
